### ISSUE TITLE
Works awesome but how to stop sending emails in tests?

### ISSUE THREAD

**Issue by justin808** [mhfs/devise-async#3]
Before using devise-async, these sort of settings in test.rb avoiding sending e-mails in tests:

  # Don't care if the mailer can't send
  config.action_mailer.raise_delivery_errors = false
  # Disable sending e-mail in testing
  config.action_mailer.perform_deliveries = false

  config.action_mailer.delivery_method = :test

Any advice on how to avoid having the tests post redis/resque messages?

**Comment by pavel-clarityhk** [comment]
This method doesn't work for me unfortunately. I am setting i in `spec_helper.rb`, flushed all Redis contents to make sure no old jobs persist there (after trying `Sidekiq::RetrySet.new.clear` in case something else was left), but email jobs for test users are still getting queued. Did anything change since 2012, is there a new way to opt out of devise-async in the test suite?

**Comment by baschtl** [comment]
Well, you could disable it altogether:
```ruby
Devise::Async.enabled = false
```

**Comment by pavel-clarityhk** [comment]
Thanks :)
